import type { Metadata } from "next";
import { Bebas_Neue, Lato } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const bebasNeue = Bebas_Neue({
	weight: "400",
	variable: "--font-bebas-neue",
	subsets: ["latin"],
});
const lato = Lato({
	weight: ["100", "300", "400", "700", "900"],
	variable: "--font-lato",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark:bg-darker dark:text-white">
			<body className={`${bebasNeue.variable} ${lato.variable} antialiased`}>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
