import type { Metadata } from "next";
import { Bebas_Neue, Lato } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import { AuthProvider } from "@/components/providers/session-provider";

const bebasNeue = Bebas_Neue({
	weight: "400",
	variable: "--font-bebas-neue",
	subsets: ["latin"],
});
const lato = Lato({
	weight: ["100", "300", "400", "700", "900"],
	variable: "--font-lato",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Findwork",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="bg-darker text-white">
			<body className={`${bebasNeue.variable} ${lato.variable} antialiased`}>
				<AuthProvider>
					<NavBar />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
